# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set settings.env to production
        run: |
          sed -i 's/^env: development/env: production/g' settings.yml

      - name: Bashly generate
        run: |
          docker run --user $(id -u):$(id -g) \
            --volume "$PWD:/app" dannyben/bashly generate

      - name: Upload artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: bws-env.sh
          path: bws-env.sh
          if-no-files-found: error
